#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M3{1,0,18.12,2
#
main.xem3: package/cfg/main.xem3.mak

clean::
	-$(RM) package/cfg/main.xem3.mak
